module.exports = {
  salutation: "#salutation",
  firstname: "#fname",
  Lastname: "#lname",
  dob: "#dob",
  address: "#address",
  city: "#city",
  state: "#state",
  zip: "#zip",
  telephone: "#tel",
  Email: "#email",
  website: "#website",
  UpdateProfileButton: "#btn-submit-profile",
  Success_Message: "#profile-form-msg",
  tabs: ".nav-item a",
  Heading: ".section-heading",
  formcontrol: ".form-control",
  InvalidFname: "#fname:invalid",
  labels: "#update-profile-form label",
};
